apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "broker.amq.io/v1alpha1",
          "kind": "ActiveMQArtemisSecurity",
          "metadata": {
            "name": "activemqartemissecurity-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "broker.amq.io/v1beta1",
          "kind": "ActiveMQArtemis",
          "metadata": {
            "name": "activemqartemis-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "broker.amq.io/v2alpha1",
          "kind": "ActiveMQArtemis",
          "metadata": {
            "name": "activemqartemis-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "broker.amq.io/v2alpha1",
          "kind": "ActiveMQArtemisAddress",
          "metadata": {
            "name": "activemqartemisaddress-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "broker.amq.io/v2alpha1",
          "kind": "ActiveMQArtemisScaledown",
          "metadata": {
            "name": "activemqartemisscaledown-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "broker.amq.io/v2alpha2",
          "kind": "ActiveMQArtemis",
          "metadata": {
            "name": "activemqartemis-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "broker.amq.io/v2alpha2",
          "kind": "ActiveMQArtemisAddress",
          "metadata": {
            "name": "activemqartemisaddress-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "broker.amq.io/v2alpha3",
          "kind": "ActiveMQArtemis",
          "metadata": {
            "name": "activemqartemis-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "broker.amq.io/v2alpha3",
          "kind": "ActiveMQArtemisAddress",
          "metadata": {
            "name": "activemqartemisaddress-sample"
          },
          "spec": {
            "addressName": "emptyAddress",
            "queueName": "",
            "removeFromBrokerOnDelete": true,
            "routingType": "multicast"
          }
        },
        {
          "apiVersion": "broker.amq.io/v2alpha4",
          "kind": "ActiveMQArtemis",
          "metadata": {
            "name": "activemqartemis-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "broker.amq.io/v2alpha5",
          "kind": "ActiveMQArtemis",
          "metadata": {
            "name": "activemqartemis-sample"
          },
          "spec": null
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.14.0+git
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: activemq-artemis-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ActiveMQArtemisAddress is the Schema for the activemqartemisaddresses
        API
      displayName: Active MQArtemis Address
      kind: ActiveMQArtemisAddress
      name: activemqartemisaddresses.broker.amq.io
      version: v2alpha1
    - description: ActiveMQArtemisAddress is the Schema for the activemqartemisaddresses
        API
      displayName: Active MQArtemis Address
      kind: ActiveMQArtemisAddress
      name: activemqartemisaddresses.broker.amq.io
      version: v2alpha2
    - description: ActiveMQArtemisAddress is the Schema for the activemqartemisaddresses
        API
      displayName: Active MQArtemis Address
      kind: ActiveMQArtemisAddress
      name: activemqartemisaddresses.broker.amq.io
      version: v2alpha3
    - description: ActiveMQArtemis is the Schema for the activemqartemises API
      displayName: Active MQArtemis
      kind: ActiveMQArtemis
      name: activemqartemises.broker.amq.io
      version: v1beta1
    - description: ActiveMQArtemis is the Schema for the activemqartemises API
      displayName: Active MQArtemis
      kind: ActiveMQArtemis
      name: activemqartemises.broker.amq.io
      version: v2alpha1
    - description: ActiveMQArtemis is the Schema for the activemqartemises API
      displayName: Active MQArtemis
      kind: ActiveMQArtemis
      name: activemqartemises.broker.amq.io
      version: v2alpha2
    - description: ActiveMQArtemis is the Schema for the activemqartemises API
      displayName: Active MQArtemis
      kind: ActiveMQArtemis
      name: activemqartemises.broker.amq.io
      version: v2alpha3
    - description: ActiveMQArtemis is the Schema for the activemqartemises API
      displayName: Active MQArtemis
      kind: ActiveMQArtemis
      name: activemqartemises.broker.amq.io
      version: v2alpha4
    - description: ActiveMQArtemis is the Schema for the activemqartemises API
      displayName: Active MQArtemis
      kind: ActiveMQArtemis
      name: activemqartemises.broker.amq.io
      version: v2alpha5
    - description: ActiveMQArtemisScaledown is the Schema for the activemqartemisscaledowns
        API
      displayName: Active MQArtemis Scaledown
      kind: ActiveMQArtemisScaledown
      name: activemqartemisscaledowns.broker.amq.io
      version: v2alpha1
    - description: ActiveMQArtemisSecurity is the Schema for the activemqartemissecurities
        API
      displayName: Active MQArtemis Security
      kind: ActiveMQArtemisSecurity
      name: activemqartemissecurities.broker.amq.io
      version: v1alpha1
  description: ArtemisCloud Operator manages ActiveMQ Artemis messaging broker in
    the cloud
  displayName: ArtemisCloud Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - broker.amq.io
          resources:
          - activemqartemisaddresses
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - broker.amq.io
          resources:
          - activemqartemisaddresses/finalizers
          verbs:
          - update
        - apiGroups:
          - broker.amq.io
          resources:
          - activemqartemisaddresses/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - broker.amq.io
          resources:
          - activemqartemises
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - broker.amq.io
          resources:
          - activemqartemises/finalizers
          verbs:
          - update
        - apiGroups:
          - broker.amq.io
          resources:
          - activemqartemises/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - broker.amq.io
          resources:
          - activemqartemisscaledowns
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - broker.amq.io
          resources:
          - activemqartemisscaledowns/finalizers
          verbs:
          - update
        - apiGroups:
          - broker.amq.io
          resources:
          - activemqartemisscaledowns/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - broker.amq.io
          resources:
          - activemqartemissecurities
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - broker.amq.io
          resources:
          - activemqartemissecurities/finalizers
          verbs:
          - update
        - apiGroups:
          - broker.amq.io
          resources:
          - activemqartemissecurities/status
          verbs:
          - get
          - patch
          - update
        serviceAccountName: activemq-artemis-controller-manager
      deployments:
      - name: activemq-artemis-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --leader-elect
                command:
                - /manager
                image: quay.io/hgao/operator:new0.20.1
                imagePullPolicy: Always
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                ports:
                - containerPort: 9443
                  name: webhook-server
                  protocol: TCP
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 200m
                    memory: 100Mi
                  requests:
                    cpu: 100m
                    memory: 20Mi
                securityContext:
                  allowPrivilegeEscalation: false
                volumeMounts:
                - mountPath: /tmp/k8s-webhook-server/serving-certs
                  name: cert
                  readOnly: true
              securityContext:
                runAsNonRoot: true
              serviceAccountName: activemq-artemis-controller-manager
              terminationGracePeriodSeconds: 10
              volumes:
              - name: cert
                secret:
                  defaultMode: 420
                  secretName: activemq-artemis-webhook-server-cert
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: activemq-artemis-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - messaging
  - cloud
  - kubernetes
  - artemis
  - integration
  links:
  - name: Activemq Artemis Operator
    url: https://activemq-artemis-operator.domain
  maintainers:
  - email: rkieley@redhat.com
    name: '''Roderick Kieley'
  - email: hgao@redhat.com
    name: Howard Gao
  - email: dbruscin@redhat.com'
    name: Domenico Francesco
  maturity: alpha
  provider:
    name: ArtemisCloud
    url: https://github.com/artemiscloud/activemq-artemis-operator
  version: 0.0.1
  webhookdefinitions:
  - admissionReviewVersions:
    - v1
    containerPort: 443
    conversionCRDs:
    - activemqartemisaddresses.broker.amq.io
    - activemqartemises.broker.amq.io
    - activemqartemisscaledowns.broker.amq.io
    - activemqartemissecurities.broker.amq.io
    deploymentName: activemq-artemis-controller-manager
    generateName: cactivemqartemisaddressesactivemqartemisesactivemqartemisscaledownsactivemqartemissecurities.kb.io
    sideEffects: None
    targetPort: 9443
    type: ConversionWebhook
    webhookPath: /convert
  - admissionReviewVersions:
    - v1
    containerPort: 443
    deploymentName: activemq-artemis-controller-manager
    failurePolicy: Fail
    generateName: mactivemqartemis.kb.io
    rules:
    - apiGroups:
      - broker.amq.io
      apiVersions:
      - v1beta1
      operations:
      - CREATE
      - UPDATE
      resources:
      - activemqartemises
    sideEffects: None
    targetPort: 9443
    type: MutatingAdmissionWebhook
    webhookPath: /mutate-broker-amq-io-v1beta1-activemqartemis
  - admissionReviewVersions:
    - v1
    containerPort: 443
    deploymentName: activemq-artemis-controller-manager
    failurePolicy: Fail
    generateName: mactivemqartemisaddress.kb.io
    rules:
    - apiGroups:
      - broker.amq.io
      apiVersions:
      - v2alpha3
      operations:
      - CREATE
      - UPDATE
      resources:
      - activemqartemisaddresses
    sideEffects: None
    targetPort: 9443
    type: MutatingAdmissionWebhook
    webhookPath: /mutate-broker-amq-io-v2alpha3-activemqartemisaddress
  - admissionReviewVersions:
    - v1
    containerPort: 443
    deploymentName: activemq-artemis-controller-manager
    failurePolicy: Fail
    generateName: mactivemqartemissecurity.kb.io
    rules:
    - apiGroups:
      - broker.amq.io
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      resources:
      - activemqartemissecurities
    sideEffects: None
    targetPort: 9443
    type: MutatingAdmissionWebhook
    webhookPath: /mutate-broker-amq-io-v1alpha1-activemqartemissecurity
  - admissionReviewVersions:
    - v1
    containerPort: 443
    deploymentName: activemq-artemis-controller-manager
    failurePolicy: Fail
    generateName: vactivemqartemis.kb.io
    rules:
    - apiGroups:
      - broker.amq.io
      apiVersions:
      - v1beta1
      operations:
      - CREATE
      - UPDATE
      resources:
      - activemqartemises
    sideEffects: None
    targetPort: 9443
    type: ValidatingAdmissionWebhook
    webhookPath: /validate-broker-amq-io-v1beta1-activemqartemis
  - admissionReviewVersions:
    - v1
    containerPort: 443
    deploymentName: activemq-artemis-controller-manager
    failurePolicy: Fail
    generateName: vactivemqartemisaddress.kb.io
    rules:
    - apiGroups:
      - broker.amq.io
      apiVersions:
      - v2alpha3
      operations:
      - CREATE
      - UPDATE
      resources:
      - activemqartemisaddresses
    sideEffects: None
    targetPort: 9443
    type: ValidatingAdmissionWebhook
    webhookPath: /validate-broker-amq-io-v2alpha3-activemqartemisaddress
  - admissionReviewVersions:
    - v1
    containerPort: 443
    deploymentName: activemq-artemis-controller-manager
    failurePolicy: Fail
    generateName: vactivemqartemissecurity.kb.io
    rules:
    - apiGroups:
      - broker.amq.io
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      resources:
      - activemqartemissecurities
    sideEffects: None
    targetPort: 9443
    type: ValidatingAdmissionWebhook
    webhookPath: /validate-broker-amq-io-v1alpha1-activemqartemissecurity
