apiVersion: broker.amq.io/v1alpha1
kind: ActiveMQArtemis
metadata:
  name: example-activemqartemis
  labels:
    ActiveMQArtemis: example-activemqartemis
    application: example-activemqartemis-app
spec:
  # Add fields here
  size: 4
  image: registry.redhat.io/amq-broker-7/amq-broker-73-openshift:7.3
  sslConfig:
    secretName: amq-app-secret
    trustStoreFilename: broker.ts
    trustStorePassword: changeit
    keystoreFilename: broker.ks
    keyStorePassword: changeit
  commonConfig:
    userName: admin
    password: admin

