apiVersion: broker.amq.io/v2alpha1
kind: ActiveMQArtemis
metadata:
  name: example-activemqartemis
  labels:
    ActiveMQArtemis: example-activemqartemis
    application: example-activemqartemis-app
spec:
  # Add fields here
  size: 4
  image: registry.redhat.io/amq7/amq-broker:7.4
  persistent: true
  commonConfig:
    userName: admin
    password: admin

