name: CI

env:
  IMAGE_NAME: activemq-artemis-operator

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install prerequisites
        run: sudo apt-get install pass

      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Build the image
        run: docker build --file ./build/Dockerfile --tag $IMAGE_NAME:latest .

      - name: Push the image
        run: >
          docker login --username=${{ secrets.QUAY_USERNAME }} --password=${{ secrets.QUAY_PASSWORD }} quay.io &&
          docker tag $IMAGE_NAME:latest quay.io/${{ secrets.QUAY_NAMESPACE }}/$IMAGE_NAME:dev.latest &&
          docker push quay.io/${{ secrets.QUAY_NAMESPACE }}/$IMAGE_NAME:dev.latest